//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDS.FLIR.SeqController.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDS.FLIR.SeqController.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Play Control과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PLAYERCTRL_GROUP_TITLE {
            get {
                return ResourceManager.GetString("PLAYERCTRL_GROUP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play/Pause과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PLAYERCTRL_PLAY_TOOLTIP {
            get {
                return ResourceManager.GetString("PLAYERCTRL_PLAY_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reverse과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PLAYERCTRL_REVERSE_CHECKBOX {
            get {
                return ResourceManager.GetString("PLAYERCTRL_REVERSE_CHECKBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backward Play Speed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PLAYERCTRL_SPEEDDOWN_TOOLTIP {
            get {
                return ResourceManager.GetString("PLAYERCTRL_SPEEDDOWN_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Forward Play Speed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PLAYERCTRL_SPEEDUP_TOOLTIP {
            get {
                return ResourceManager.GetString("PLAYERCTRL_SPEEDUP_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string PLAYERCTRL_STOP_TOOLTIP {
            get {
                return ResourceManager.GetString("PLAYERCTRL_STOP_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recording Rate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RECORDSETTINGS_FRAMERATEGROUP_TITLE {
            get {
                return ResourceManager.GetString("RECORDSETTINGS_FRAMERATEGROUP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Post.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RECORDSETTINGS_POST_CHECKBOX {
            get {
                return ResourceManager.GetString("RECORDSETTINGS_POST_CHECKBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   secs과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RECORDSETTINGS_POST_LABEL {
            get {
                return ResourceManager.GetString("RECORDSETTINGS_POST_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set Pre.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RECORDSETTINGS_PRE_CHECKBOX {
            get {
                return ResourceManager.GetString("RECORDSETTINGS_PRE_CHECKBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   secs과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RECORDSETTINGS_PRE_LABEL {
            get {
                return ResourceManager.GetString("RECORDSETTINGS_PRE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   every과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RECORDSETTINGS_RATEFRAME_CHECKBOX {
            get {
                return ResourceManager.GetString("RECORDSETTINGS_RATEFRAME_CHECKBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   th frame과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RECORDSETTINGS_RATEFRAME_LABEL {
            get {
                return ResourceManager.GetString("RECORDSETTINGS_RATEFRAME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RECORDSETTINGS_RATESEC_CHECKBOX {
            get {
                return ResourceManager.GetString("RECORDSETTINGS_RATESEC_CHECKBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   frames per seconds과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RECORDSETTINGS_RATESEC_LABEL {
            get {
                return ResourceManager.GetString("RECORDSETTINGS_RATESEC_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save per size과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RECORDSETTINGS_SAVEPERSIZE_TITLE {
            get {
                return ResourceManager.GetString("RECORDSETTINGS_SAVEPERSIZE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pre/Post Recording과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RECORDSETTINGS_SPACEGGROUP_TITLE {
            get {
                return ResourceManager.GetString("RECORDSETTINGS_SPACEGGROUP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RECORDSETTINGS_TRIGEND_LABEL {
            get {
                return ResourceManager.GetString("RECORDSETTINGS_TRIGEND_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Triggers과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RECORDSETTINGS_TRIGGERSGROUP_TITLE {
            get {
                return ResourceManager.GetString("RECORDSETTINGS_TRIGGERSGROUP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RECORDSETTINGS_TRIGSTART_LABEL {
            get {
                return ResourceManager.GetString("RECORDSETTINGS_TRIGSTART_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type :과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RECORDSETTINGS_TRIGTYPE_LABEL {
            get {
                return ResourceManager.GetString("RECORDSETTINGS_TRIGTYPE_LABEL", resourceCulture);
            }
        }
    }
}
